### ISSUE TITLE
Unban

### ISSUE THREAD

**Issue by Ale32bit** [inklit/SwitchCraft#7]
Sooo, I know I'm banned for defacing world with lasers.
I can't may not convince you that the ban is invalid since I made it and you know.

I was a bored idiot when I defaced that zone and I wanted to test lasers.

I'm not so creative at making unban appeals.

Hope you unban me.
Thanks :)

(Well, you might not gonna unban me. At least I tried)
P.S. I miss you all

**Comment by inklit** [comment]
Approved.
